using System;
using System.Linq;
using System.Collections.Generic;
using RayFire.DotNet;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

namespace D
{
    /// <summary>
    /// Component for shattering meshes into fragments.
    /// Supports various fragmentation types like Voronoi, Splinters, Bricks, etc.
    /// </summary>
    [AddComponentMenu ("D/D Shatter")]
    public class DShatter : MonoBehaviour
    {
        /// <summary>
        /// Mode for handling the last generated fragments.
        /// </summary>
        public enum FragLastMode
        {
            /// <summary>
            /// Create new fragments.
            /// </summary>
            New    = 0,
            /// <summary>
            /// Apply to the last generated fragments.
            /// </summary>
            ToLast = 1
        }

        /// <summary>
        /// Type of fragmentation algorithm to use.
        /// </summary>
        public FragType type = FragType.Voronoi;

        /// <summary>
        /// Settings for Voronoi fragmentation.
        /// </summary>
        public RFVoronoi voronoi = new RFVoronoi();

        /// <summary>
        /// Settings for Splinters fragmentation.
        /// </summary>
        public RFSplinters splinters = new RFSplinters();

        /// <summary>
        /// Settings for Slabs fragmentation.
        /// </summary>
        public RFSplinters slabs = new RFSplinters();

        /// <summary>
        /// Settings for Radial fragmentation.
        /// </summary>
        public RFRadial radial = new RFRadial();

        /// <summary>
        /// Settings for Hexagon fragmentation.
        /// </summary>
        public RFHexagon hexagon = new RFHexagon();

        /// <summary>
        /// Settings for Custom fragmentation.
        /// </summary>
        public RFCustom custom = new RFCustom();

        /// <summary>
        /// Settings for Mirrored fragmentation.
        /// </summary>
        public RFMirrored mirrored = new RFMirrored();

        /// <summary>
        /// Settings for Slice fragmentation.
        /// </summary>
        public RFSlice slice = new RFSlice();

        /// <summary>
        /// Settings for Bricks fragmentation.
        /// </summary>
        public RFBricks bricks = new RFBricks();

        /// <summary>
        /// Settings for Voxels fragmentation.
        /// </summary>
        public RFVoxels voxels = new RFVoxels();

        /// <summary>
        /// Settings for Tets fragmentation.
        /// </summary>
        public RFTets tets = new RFTets();

        /// <summary>
        /// Current fragmentation mode (Editor/Runtime).
        /// </summary>
        public FragmentMode mode = FragmentMode.Editor;

        /// <summary>
        /// Material properties for the inner surface of fragments.
        /// </summary>
        public RFSurface material = new RFSurface();

        /// <summary>
        /// Settings for clustering fragments.
        /// </summary>
        public RFShatterCluster clusters = new RFShatterCluster();

        /// <summary>
        /// Advanced settings for shattering.
        /// </summary>
        public RFShatterAdvanced advanced = new RFShatterAdvanced();

        /// <summary>
        /// Settings for exporting meshes.
        /// </summary>
        public RFMeshExport export = new RFMeshExport();

        /// <summary>
        /// Show the center point in the editor.
        /// </summary>
        public bool showCenter;

        /// <summary>
        /// Custom center position for fragmentation.
        /// </summary>
        public Vector3 centerPosition;

        /// <summary>
        /// Custom center direction/rotation.
        /// </summary>
        public Quaternion centerDirection;

        /// <summary>
        /// Cached transform component.
        /// </summary>
        public Transform transForm;

        /// <summary>
        /// Cached MeshFilter component.
        /// </summary>
        public MeshFilter meshFilter;

        /// <summary>
        /// Cached MeshRenderer component.
        /// </summary>
        public MeshRenderer meshRenderer;

        /// <summary>
        /// Cached SkinnedMeshRenderer component.
        /// </summary>
        public SkinnedMeshRenderer skinnedMeshRend;

        /// <summary>
        /// List of MeshFilters for multiple mesh fragmentation.
        /// </summary>
        public List<MeshFilter> meshFilters;

        [NonSerialized] Mesh[] meshes;
        [NonSerialized] Vector3[] pivots;
        [NonSerialized] RFDictionary[] rfOrigSubMeshIds;

        /// <summary>
        /// List of root objects generated by shattering.
        /// </summary>
        public List<Transform> rootChildList = new List<Transform>();

        /// <summary>
        /// List containing all generated fragments.
        /// </summary>
        public List<GameObject> fragmentsAll = new List<GameObject>();

        /// <summary>
        /// List containing fragments from the last operation.
        /// </summary>
        public List<GameObject> fragmentsLast = new List<GameObject>();

        /// <summary>
        /// Array of materials used by the object.
        /// </summary>
        public Material[] materials;

        /// <summary>
        /// Internal mode index.
        /// </summary>
        public int shatterMode = 1;

        /// <summary>
        /// Enable color preview for fragments.
        /// </summary>
        public bool colorPreview;

        /// <summary>
        /// Enable scale preview for fragments.
        /// </summary>
        public bool scalePreview = true;

        /// <summary>
        /// Scale value for previewing.
        /// </summary>
        public float previewScale;

        /// <summary>
        /// Size of the object bounds.
        /// </summary>
        public float size;

        /// <summary>
        /// Rescale factor for small objects.
        /// </summary>
        public float rescaleFix = 1f;

        /// <summary>
        /// Original scale of the object.
        /// </summary>
        public Vector3 originalScale;

        /// <summary>
        /// Bounds of the object.
        /// </summary>
        public Bounds bound;

        /// <summary>
        /// State for resetting properties.
        /// </summary>
        public bool resetState;

        /// <summary>
        /// Enable interactive fragmentation mode.
        /// </summary>
        public bool interactive;

        /// <summary>
        /// Reference to interactive shatter data.
        /// </summary>
        public RFShatter shatterInt;

        /// <summary>
        /// Interactive game object.
        /// </summary>
        public GameObject intGo;

        /// <summary>
        /// Interactive MeshFilter.
        /// </summary>
        public MeshFilter intMf;

        /// <summary>
        /// Interactive MeshRenderer.
        /// </summary>
        public MeshRenderer intMr;

        static float minSize = 0.01f;

        /// <summary>
        /// Resets the component to default state.
        /// </summary>
        private void Reset()
        {
            InteractiveStop();
            ResetCenter();
        }

        /// <summary>
        /// Initializes variables before fragmentation.
        /// </summary>
        void SetVariables()
        {
            size             = 0f;
            rescaleFix       = 1f;
            originalScale    = transForm.localScale;
            rfOrigSubMeshIds = null;
        }

        /// <summary>
        /// Performs checks to see if fragmentation is possible.
        /// </summary>
        /// <returns>True if checks pass.</returns>
        bool MainCheck()
        {
            if (gameObject.scene.rootCount == 0)
            {
                Debug.Log ("D Shatter: " + name + " Can't fragment prefab because prefab unable to store Unity mesh. Fragment prefab in scene.", gameObject);
                return false;
            }

            if (advanced.combineChildren == false)
                if (SingleMeshCheck() == false)
                    return false;

            if (advanced.combineChildren == true)
            {
                if (meshFilters.Count == 1)
                    if (SingleMeshCheck() == false)
                        return false;

                if (meshFilters.Count > 0)
                    for (int i = meshFilters.Count - 1; i >= 0; i--)
                        if (meshFilters[i].sharedMesh == null)
                        {
                            Debug.Log ("D Shatter: " + meshFilters[i].name + " MeshFilter has no Mesh, object excluded.", meshFilters[i].gameObject);
                            meshFilters.RemoveAt (i);
                        }

                if (meshFilters.Count > 0)
                    for (int i = meshFilters.Count - 1; i >= 0; i--)
                        if (meshFilters[i].sharedMesh.isReadable == false)
                        {
                            Debug.Log ("D Shatter: " + meshFilters[i].name + " Mesh is not Readable, object excluded.", meshFilters[i].gameObject);
                            meshFilters.RemoveAt (i);
                        }

                if (meshFilters.Count == 0)
                    return false;
            }

            return true;
        }

        /// <summary>
        /// Checks specific to single mesh fragmentation.
        /// </summary>
        /// <returns>True if checks pass.</returns>
        bool SingleMeshCheck()
        {
            if (meshFilter == null && skinnedMeshRend == null)
            {
                Debug.Log ("D Shatter: " + name + " Object has no mesh to fragment.", gameObject);
                return false;
            }

            if (meshFilter != null)
            {
                if (meshFilter.sharedMesh == null)
                {
                    Debug.Log ("D Shatter: " + name + " Object has no mesh to fragment.", gameObject);
                    return false;
                }

                if (meshFilter.sharedMesh.isReadable == false)
                {
                    Debug.Log ("D Shatter: " + name + "Mesh is not readable. Open Import Settings and turn On Read/Write Enabled", gameObject);
                    return false;
                }
            }

            if (skinnedMeshRend != null && skinnedMeshRend.sharedMesh == null)
            {
                Debug.Log ("D Shatter: " + name + " Object has no mesh to fragment.", gameObject);
                return false;
            }

            return true;
        }

        /// <summary>
        /// Caches necessary components for fragmentation.
        /// </summary>
        /// <returns>True if components found and valid.</returns>
        bool DefineComponents()
        {
            transForm       = GetComponent<Transform>();
            meshFilter      = GetComponent<MeshFilter>();
            meshRenderer    = GetComponent<MeshRenderer>();
            skinnedMeshRend = GetComponent<SkinnedMeshRenderer>();

            meshFilters = new List<MeshFilter>();
            if (advanced.combineChildren == true)
                meshFilters = GetComponentsInChildren<MeshFilter>().ToList();

            if (MainCheck() == false)
                return false;

            if (skinnedMeshRend == null)
            {
                if (meshRenderer == null)
                    meshRenderer = gameObject.AddComponent<MeshRenderer>();
                bound = meshRenderer.bounds;
            }

            if (skinnedMeshRend != null)
                bound = skinnedMeshRend.bounds;

            return true;
        }

        /// <summary>
        /// Gets the bounds of the object.
        /// </summary>
        /// <returns>Bounds of the mesh.</returns>
        public Bounds GetBound()
        {
            if (meshRenderer == null)
            {
                meshRenderer = GetComponent<MeshRenderer>();
                if (meshRenderer != null)
                    return meshRenderer.bounds;
            }
            else
                return meshRenderer.bounds;

            if (skinnedMeshRend == null)
            {
                skinnedMeshRend = GetComponent<SkinnedMeshRenderer>();
                if (skinnedMeshRend != null)
                    return skinnedMeshRend.bounds;
            }

            return new Bounds();
        }

        /// <summary>
        /// Fragments the object based on current settings.
        /// </summary>
        /// <param name="fragmentMode">Mode determining how to handle new fragments.</param>
        public void Fragment(FragLastMode fragmentMode = FragLastMode.New)
        {
            if (PreCache() == false)
                return;

            RFFragment.CacheMeshes (ref meshes, ref pivots, ref rfOrigSubMeshIds, this);

            if (meshes == null)
                return;

            if (fragmentMode == FragLastMode.ToLast)
            {
                if (rootChildList[rootChildList.Count - 1] != null)
                    fragmentsLast = CreateFragments (rootChildList[rootChildList.Count - 1]);
                else
                    fragmentMode = FragLastMode.New;
            }

            if (fragmentMode == FragLastMode.New)
                fragmentsLast = CreateFragments();

            PostFragments();
        }

        /// <summary>
        /// Prepares for fragmentation by caching components and checking scale.
        /// </summary>
        /// <returns>True if successful.</returns>
        bool PreCache()
        {
            if (DefineComponents() == false)
                return false;

            SetVariables();

            ScaleCheck();

            return true;
        }

        /// <summary>
        /// Creates game objects for the generated fragments.
        /// </summary>
        /// <param name="root">Optional root transform for fragments.</param>
        /// <returns>List of created fragment GameObjects.</returns>
        List<GameObject> CreateFragments(Transform root = null)
        {
            if (meshes == null)
                return null;

            GameObject[] fragArray = new GameObject[meshes.Length];

            if (root == null)
            {
                GameObject rootGo = new GameObject (gameObject.name + "_root");
                rootGo.transform.position = transForm.position;
                rootGo.transform.rotation = transForm.rotation;
                rootGo.tag                = gameObject.tag;
                rootGo.layer              = gameObject.layer;
                root                      = rootGo.transform;
                rootChildList.Add (root);
            }

            GameObject fragInstance;
            if (advanced.copyComponents == true)
            {
                fragInstance                      = Instantiate (gameObject);
                fragInstance.transform.rotation   = Quaternion.identity;
                fragInstance.transform.localScale = Vector3.one;

                DestroyImmediate (fragInstance.GetComponent<DShatter>());
            }
            else
            {
                fragInstance = new GameObject();
                fragInstance.AddComponent<MeshFilter>();
                fragInstance.AddComponent<MeshRenderer>();
            }

            if (advanced.combineChildren == false)
                materials = skinnedMeshRend != null
                    ? skinnedMeshRend.sharedMaterials
                    : meshRenderer.sharedMaterials;

            string baseName = gameObject.name + "_sh_";

            MeshFilter   mf;
            GameObject   go;
            MeshCollider mc;
            MeshRenderer rn;
            for (int i = 0; i < meshes.Length; ++i)
            {
                if (rescaleFix != 1f)
                    RFFragment.RescaleMesh (meshes[i], rescaleFix);

                go                      = Instantiate (fragInstance);
                go.transform.localScale = Vector3.one;

                rn = go.GetComponent<MeshRenderer>();
                RFSurface.SetMaterial (rfOrigSubMeshIds, materials, material, rn, i, meshes.Length);

                go.name               = baseName + (i + 1);
                go.transform.position = root.transform.position + (pivots[i] / rescaleFix);
                go.transform.parent   = root.transform;
                go.tag                = gameObject.tag;
                go.layer              = gameObject.layer;

                mf                 = go.GetComponent<MeshFilter>();
                mf.sharedMesh      = meshes[i];
                mf.sharedMesh.name = go.name;

                mc = go.GetComponent<MeshCollider>();
                if (mc != null)
                    mc.sharedMesh = meshes[i];

                fragArray[i] = go;
            }

            root.transform.parent = transForm.parent;

            if (skinnedMeshRend == null)
                root.transform.localScale = Vector3.one;

            DestroyImmediate (fragInstance);

            meshes           = null;
            pivots           = null;
            rfOrigSubMeshIds = null;

            return fragArray.ToList();
        }

        /// <summary>
        /// Performs operations after fragments are created (e.g. limitations, collecting list).
        /// </summary>
        void PostFragments()
        {
            RFShatterAdvanced.Limitations (this);

            fragmentsAll.AddRange (fragmentsLast);

            transForm.localScale = originalScale;
        }

        /// <summary>
        /// Recursively fragments a specific fragment based on limitations.
        /// </summary>
        /// <param name="ind">Index of the fragment.</param>
        public void LimitationFragment(int ind)
        {
            DShatter shat = fragmentsLast[ind].AddComponent<DShatter>();
            shat.voronoi.amount = 10;

            shat.Fragment();

            if (shat.fragmentsLast.Count > 0)
            {
                fragmentsLast.AddRange (shat.fragmentsLast);
                DestroyImmediate (shat.gameObject);
                fragmentsLast.RemoveAt (ind);

                foreach (var frag in shat.fragmentsLast)
                    frag.transform.parent = rootChildList[rootChildList.Count - 1];
                DestroyImmediate (shat.rootChildList[rootChildList.Count - 1].gameObject);
            }
        }

        /// <summary>
        /// Deletes the fragments generated by the last operation.
        /// </summary>
        /// <param name="destroyMode">0: Destroy with root, 1: Destroy fragments only.</param>
        public void DeleteFragmentsLast(int destroyMode = 0)
        {
            if (destroyMode == 1)
                for (int i = fragmentsLast.Count - 1; i >= 0; i--)
                    if (fragmentsLast[i] != null)
                        DestroyImmediate (fragmentsLast[i]);

            fragmentsLast.Clear();
            for (int i = fragmentsAll.Count - 1; i >= 0; i--)
                if (fragmentsAll[i] == null)
                    fragmentsAll.RemoveAt (i);

            for (int i = rootChildList.Count - 1; i >= 0; i--)
                if (rootChildList[i] == null)
                    rootChildList.RemoveAt (i);

            if (rootChildList.Count == 0)
                return;

            if (destroyMode == 0)
            {
                DestroyImmediate (rootChildList[rootChildList.Count - 1].gameObject);

                rootChildList.RemoveAt (rootChildList.Count - 1);
            }

            for (int i = fragmentsAll.Count - 1; i >= 0; i--)
                if (fragmentsAll[i] == null)
                    fragmentsAll.RemoveAt (i);
        }

        /// <summary>
        /// Deletes all generated fragments and roots.
        /// </summary>
        public void DeleteFragmentsAll()
        {
            fragmentsLast.Clear();
            fragmentsAll.Clear();

            for (int i = rootChildList.Count - 1; i >= 0; i--)
                if (rootChildList[i] != null)
                    DestroyImmediate (rootChildList[i].gameObject);
            rootChildList.Clear();
        }

        /// <summary>
        /// Resets the center position/direction helpers.
        /// </summary>
        public void ResetCenter()
        {
            centerPosition  = Vector3.zero;
            centerDirection = Quaternion.identity;

            Renderer rend = GetComponent<Renderer>();
            if (rend != null)
                centerPosition = transform.InverseTransformPoint (rend.bounds.center);
        }

        /// <summary>
        /// Checks if the object is too small and needs rescaling for fragmentation.
        /// </summary>
        void ScaleCheck()
        {
            if (meshRenderer != null)
                size = meshRenderer.bounds.size.magnitude;
            if (skinnedMeshRend != null)
                size = skinnedMeshRend.bounds.size.magnitude;

            if (size != 0f && size < minSize)
            {
                rescaleFix = 1f / size;

                Vector3 newScale = transForm.localScale * rescaleFix;
                transForm.localScale = newScale;

                Debug.Log ("Warning. Object " + name + " is too small.");
            }
        }

        /// <summary>
        /// Resets the scale of the object and fragments.
        /// </summary>
        /// <param name="scaleValue">Scale value to check against (usually 0).</param>
        public void ResetScale(float scaleValue)
        {
            if (resetState == true && scaleValue == 0f)
            {
                if (skinnedMeshRend != null)
                    skinnedMeshRend.enabled = true;

                if (meshRenderer != null)
                    meshRenderer.enabled = true;

                if (fragmentsLast.Count > 0)
                    foreach (GameObject fragment in fragmentsLast)
                        if (fragment != null)
                            fragment.transform.localScale = Vector3.one;

                resetState = false;
            }
        }

        /// <summary>
        /// Copies shatter components from a source Rigid object to targets.
        /// </summary>
        /// <param name="source">Source rigid object.</param>
        /// <param name="targets">List of target rigid objects.</param>
        public static void CopyRootMeshShatter(DRigid source, List<DRigid> targets)
        {
            if (source.meshDemolition.sht == null)
                return;

            for (int i = 0; i < targets.Count; i++)
            {
                targets[i].meshDemolition.sht = targets[i].gameObject.AddComponent<DShatter>();
                targets[i].meshDemolition.sht.CopyFrom (source.meshDemolition.sht);
            }
        }

        /// <summary>
        /// Copies properties from another DShatter component.
        /// </summary>
        /// <param name="shatter">Source component.</param>
        void CopyFrom(DShatter shatter)
        {
            type = shatter.type;

            voronoi   = new RFVoronoi (shatter.voronoi);
            splinters = new RFSplinters (shatter.splinters);
            slabs     = new RFSplinters (shatter.slabs);
            radial    = new RFRadial (shatter.radial);
            custom    = new RFCustom (shatter.custom);
            slice     = new RFSlice (shatter.slice);
            tets      = new RFTets (shatter.tets);

            mode = shatter.mode;
            material.CopyFrom (shatter.material);
            clusters = new RFShatterCluster (shatter.clusters);
            advanced = new RFShatterAdvanced (shatter.advanced);
        }

        /// <summary>
        /// Creates an interactive object for previewing.
        /// </summary>
        void InteractiveCreate()
        {
            if (intGo == null)
            {
                intGo           = new GameObject (name + "_Interactive");
                intMf           = intGo.AddComponent<MeshFilter>();
                
                intGo.transform.position = transForm.position;
                
                intGo.tag   = gameObject.tag;
                intGo.layer = gameObject.layer;
            }
            if (meshRenderer != null)
            {
                if (intMr == null)
                {
                    intMr                 = intGo.AddComponent<MeshRenderer>();
                    intMr.sharedMaterials = meshRenderer.sharedMaterials;
                }
            }
            else if (skinnedMeshRend != null)
            {
            }
        }

        /// <summary>
        /// Starts interactive fragmentation mode.
        /// </summary>
        public void InteractiveStart()
        {
            if (PreCache() == false)
            {
                OriginalRenderer(true);;
                return;
            }

            InteractiveCreate();

            shatterInt = RFFragment.CacheMeshes (ref meshes, ref pivots, ref rfOrigSubMeshIds, this);

            if (meshes == null)
            {
                OriginalRenderer(true);;
                return;
            }

            List<Dictionary<int, int>> ids = new List<Dictionary<int, int>>();
            for (int i = 0; i < rfOrigSubMeshIds.Length; i++)
            {
                Dictionary<int, int> d = new Dictionary<int, int>
                {
                    {rfOrigSubMeshIds[i].keys[0], rfOrigSubMeshIds[i].values[0]}
                };
                ids.Add (d);
            }
            
            intMf.sharedMesh = RFShatter.WeldMeshes (ref meshes, ref pivots, ref ids, PreviewScale());

            OriginalRenderer(false);
        }

        /// <summary>
        /// Updates interactive preview when properties change.
        /// </summary>
        public void InteractiveChange()
        {
            if (interactive == false)
                return;
            
            if (PreCache() == false)
            {
                OriginalRenderer(true);;
                return;
            }

            shatterInt = RFFragment.CacheMeshes (ref meshes, ref pivots, ref rfOrigSubMeshIds, this);

            if (meshes == null)
            {
                OriginalRenderer(true);;
                return;
            }

            List<Dictionary<int, int>> ids = new List<Dictionary<int, int>>();
            for (int i = 0; i < rfOrigSubMeshIds.Length; i++)
            {
                Dictionary<int, int> d = new Dictionary<int, int>
                {
                    {rfOrigSubMeshIds[i].keys[0], rfOrigSubMeshIds[i].values[0]}
                };
                ids.Add (d);
            }

            intMf.sharedMesh = RFShatter.WeldMeshes (ref meshes, ref pivots, ref ids, PreviewScale());
            
            OriginalRenderer(false);
        }

        /// <summary>
        /// Finalizes interactive fragmentation.
        /// </summary>
        public void InteractiveFragment()
        {
            fragmentsLast = CreateFragments();

            PostFragments();

            InteractiveStop();
        }

        /// <summary>
        /// Stops interactive mode and reverts changes.
        /// </summary>
        public void InteractiveStop()
        {
            OriginalRenderer(true);
            
            if (intGo != null)
                DestroyImmediate (intGo);
            
            intGo       = null;
            intMf       = null;
            intMr       = null;
            shatterInt  = null;
            interactive = false;
        }

        /// <summary>
        /// Sets the state of the original renderer.
        /// </summary>
        /// <param name="state">Enabled state.</param>
        void OriginalRenderer(bool state)
        {
            if (meshRenderer != null)
                meshRenderer.enabled = state;
            if (skinnedMeshRend != null)
                skinnedMeshRend.enabled = state;
        }
        
        /// <summary>
        /// Resets interactive mode.
        /// </summary>
        public void InteractiveReset()
        {
            if (interactive == true)
            {
                InteractiveStop();
            }
        }

        /// <summary>
        /// Calculates the preview scale.
        /// </summary>
        /// <returns>Scale factor.</returns>
        public float PreviewScale()
        {
            if (scalePreview == false)
                return 1f;
            return Mathf.Lerp (1f, 0.3f, previewScale);
        }
    }
}
